import type { BrotherQLDevice } from './types.js';

const MASS_STORAGE_PIDS = new Set([0x20aa, 0x20ab]);

export const DEVICES = {
  QL_820NWB: {
    name: 'QL-820NWB',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp', 'serial', 'web-serial'],
    vid: 0x04f9,
    pid: 0x20a7,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: true,
    network: 'wifi+wired',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_820NWBc: {
    name: 'QL-820NWBc',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp', 'serial', 'web-serial'],
    vid: 0x04f9,
    pid: 0x209d,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: true,
    network: 'wifi+wired',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_810W: {
    name: 'QL-810W',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x209c,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: true,
    network: 'wifi',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_800: {
    name: 'QL-800',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x209b,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: true,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_720NW: {
    name: 'QL-720NW',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x2045,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'wired',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_710W: {
    name: 'QL-710W',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x2044,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'wifi',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_700: {
    name: 'QL-700',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2042,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_600: {
    name: 'QL-600',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2100,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_580N: {
    name: 'QL-580N',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x201b,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'wired',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_570: {
    name: 'QL-570',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2019,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_560: {
    name: 'QL-560',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2018,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: false,
    editorLite: false,
  },
  QL_550: {
    name: 'QL-550',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2016,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: false,
    compression: false,
    editorLite: false,
  },
  QL_500: {
    name: 'QL-500',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2013,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: false,
    compression: false,
    editorLite: false,
  },
  QL_650TD: {
    name: 'QL-650TD',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x201c,
    headPins: 720,
    bytesPerRow: 90,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_1100: {
    name: 'QL-1100',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x20a8,
    headPins: 1296,
    bytesPerRow: 162,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: true,
    massStoragePid: 0x20aa,
  },
  QL_1110NWB: {
    name: 'QL-1110NWB',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x20a9,
    headPins: 1296,
    bytesPerRow: 162,
    twoColor: false,
    network: 'wifi+wired',
    autocut: true,
    compression: true,
    editorLite: true,
    massStoragePid: 0x20ab,
  },
  QL_1115NWB: {
    name: 'QL-1115NWB',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x20ac,
    headPins: 1296,
    bytesPerRow: 162,
    twoColor: false,
    network: 'wifi+wired',
    autocut: true,
    compression: true,
    editorLite: true,
  },
  QL_1050: {
    name: 'QL-1050',
    family: 'brother-ql',
    transports: ['usb', 'webusb'],
    vid: 0x04f9,
    pid: 0x2027,
    headPins: 1296,
    bytesPerRow: 162,
    twoColor: false,
    network: 'none',
    autocut: true,
    compression: true,
    editorLite: false,
  },
  QL_1060N: {
    name: 'QL-1060N',
    family: 'brother-ql',
    transports: ['usb', 'webusb', 'tcp'],
    vid: 0x04f9,
    pid: 0x2028,
    headPins: 1296,
    bytesPerRow: 162,
    twoColor: false,
    network: 'wired',
    autocut: true,
    compression: true,
    editorLite: false,
  },
} as const satisfies Record<string, BrotherQLDevice>;

export function findDevice(vid: number, pid: number): BrotherQLDevice | undefined {
  return Object.values(DEVICES).find(d => d.vid === vid && d.pid === pid);
}

export function isMassStorageMode(pid: number): boolean {
  return MASS_STORAGE_PIDS.has(pid);
}
