#!/usr/bin/env node
// Aggregates packages/core/data/devices/*.json5 + packages/core/data/media.json5
// into the runtime artifacts:
//
//   - data/devices.json — published JSON form of the device registry.
//   - data/media.json   — published JSON form of the media registry.
//   - src/devices.generated.ts — typed re-export consumed by src/devices.ts.
//   - src/media.generated.ts   — typed re-export consumed by src/media.ts.
//
// PR 1 of the contracts-shape migration: this is a pass-through
// aggregator. Entries keep the legacy flat `BrotherQLDevice` /
// `BrotherQLMedia` shape; the generated TS satisfies
// `Record<string, BrotherQLDevice>` / `Record<number, BrotherQLMedia>`
// so runtime behavior is byte-identical to the previous in-source
// const. PR 2 swaps in the contracts `DeviceRegistry` shape and
// adds shape validation here.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import JSON5 from 'json5';

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(SCRIPT_DIR, '..');
const CORE_PKG = resolve(REPO_ROOT, 'packages/core');
const DEVICES_DIR = resolve(CORE_PKG, 'data/devices');
const MEDIA_FILE = resolve(CORE_PKG, 'data/media.json5');
const DEVICES_OUT = resolve(CORE_PKG, 'data/devices.json');
const MEDIA_OUT = resolve(CORE_PKG, 'data/media.json');
const DEVICES_TS = resolve(CORE_PKG, 'src/devices.generated.ts');
const MEDIA_TS = resolve(CORE_PKG, 'src/media.generated.ts');

const DRIVER = 'brother-ql';
const SCHEMA_VERSION = 0;

const errors = [];
const fail = msg => errors.push(msg);

function readJson5(path) {
  return JSON5.parse(readFileSync(path, 'utf8'));
}

function loadDevices() {
  const files = readdirSync(DEVICES_DIR)
    .filter(f => f.endsWith('.json5'))
    .sort();

  const devices = {};
  const seenPids = new Map();

  for (const filename of files) {
    const path = join(DEVICES_DIR, filename);
    const key = basename(filename, '.json5');
    let entry;
    try {
      entry = readJson5(path);
    } catch (err) {
      fail(`${filename}: parse error — ${err.message}`);
      continue;
    }
    if (typeof entry?.name !== 'string') {
      fail(`${filename}: missing string \`name\``);
      continue;
    }
    if (entry.family !== DRIVER) {
      fail(`${filename}: family must be "${DRIVER}" (got ${JSON.stringify(entry.family)})`);
    }
    if (typeof entry.pid !== 'number') {
      fail(`${filename}: \`pid\` must be a number`);
    } else {
      const collision = seenPids.get(entry.pid);
      if (collision) fail(`${filename}: pid ${entry.pid} already used by \`${collision}\``);
      else seenPids.set(entry.pid, key);
    }
    devices[key] = entry;
  }

  return devices;
}

function loadMedia() {
  const list = readJson5(MEDIA_FILE);
  if (!Array.isArray(list)) {
    fail('media.json5: top-level must be an array');
    return [];
  }
  const seenIds = new Set();
  for (const [i, m] of list.entries()) {
    if (m?.id == null) fail(`media[${i}]: missing \`id\``);
    else if (seenIds.has(m.id)) fail(`media[${i}]: duplicate id \`${m.id}\``);
    else seenIds.add(m.id);
    if (typeof m?.widthMm !== 'number') fail(`media[${i}]: \`widthMm\` must be a number`);
    if (typeof m?.type !== 'string') fail(`media[${i}]: \`type\` must be a string`);
  }
  return list;
}

function writeJson(path, value) {
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, JSON.stringify(value, null, 2) + '\n', 'utf8');
}

function writeGeneratedTs(path, header, body) {
  const content = `// AUTO-GENERATED by scripts/compile-data.mjs — do not edit by hand.
// Regenerate with \`pnpm --filter @thermal-label/brother-ql-core compile-data\`.
${header}

${body}
`;
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');
}

const devices = loadDevices();
const media = loadMedia();

if (errors.length > 0) {
  console.error(`[compile-data] ${errors.length} error(s):`);
  for (const e of errors) console.error('  - ' + e);
  process.exit(1);
}

const deviceRegistry = {
  schemaVersion: SCHEMA_VERSION,
  driver: DRIVER,
  devices,
};
const mediaRegistry = {
  schemaVersion: SCHEMA_VERSION,
  driver: DRIVER,
  media,
};

writeJson(DEVICES_OUT, deviceRegistry);
writeJson(MEDIA_OUT, mediaRegistry);

writeGeneratedTs(
  DEVICES_TS,
  "import type { BrotherQLDevice } from './types.js';",
  `export const DEVICES = ${JSON.stringify(devices, null, 2)} as const satisfies Record<string, BrotherQLDevice>;`,
);

const mediaObject = Object.fromEntries(media.map(m => [m.id, m]));
writeGeneratedTs(
  MEDIA_TS,
  "import type { BrotherQLMedia } from './types.js';",
  `const MEDIA_BY_ID: Record<number, BrotherQLMedia> = ${JSON.stringify(mediaObject, null, 2)};

export const MEDIA: Record<number, BrotherQLMedia> = MEDIA_BY_ID;
export const MEDIA_LIST: readonly BrotherQLMedia[] = Object.freeze(${JSON.stringify(media, null, 2)});`,
);

const deviceCount = Object.keys(devices).length;
console.log(
  `[compile-data] OK — ${deviceCount} devices, ${media.length} media entries → data/devices.json, data/media.json`,
);
